import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import AOSProvider from '@/components/AOSProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossOrigin=""
        />
      </head>

      <body className={`${geistSans.variable} font-sans antialiased`}>
      
        <AOSProvider>
          {children}
        </AOSProvider>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}