import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AOSProvider from '@/components/AOSProvider';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Pindahkan className ke dalam tag body */}
      <body className={`${geistSans.variable} font-sans antialiased`}>
        {/* Bungkus children dengan AOSProvider di sini */}
        <AOSProvider>
          {children}
        </AOSProvider>
      </body>
    </html>
  );
}